---
name: Linting

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      # check-out repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      # install requirements (including dev dependencies)
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          make deps
      # run linters
      - name: Run linters
        run: |
          set -o pipefail
          make lint
          