---
name: Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.ADMIN_TOKEN }}
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install semver deps
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release
      - name: Run semantic release
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          set -o pipefail
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          semantic-release publish -v DEBUG -D commit_author="github-actions <action@github.com>"
